CREATE TABLE "order" (
  id UUID PRIMARY KEY,
  customer_id UUID NOT NULL,
  product_id UUID NOT NULL,
  quantity INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE "order"
ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'PENDING';